### ISSUE TITLE
support groups in grants in addition to users and roles?

### ISSUE THREAD

**Issue by joemiller** [dcoker/biscuit#4]
Would it be possible to support IAM groups in addition to users and roles? ex:

```
$ biscuit kms grants create --grantee-principal group/developers -f secrets.data foo
InvalidArnException: ARN does not refer to a valid principal: arn:aws:iam::12345:user/group/developers
```

**Comment by philipn** [comment]
@joemiller The AWS KMS API doesn't appear to allow for IAM groups to be used in a grant (reference: http://docs.aws.amazon.com/kms/latest/APIReference/API_CreateGrant.html#API_CreateGrant_RequestSyntax, "Valid AWS principals include AWS accounts (root), IAM users, federated users, and assumed role users")

**Comment by dcoker** [comment]
AWS does not allow IAM groups to be specified as principals in KMS grants or KMS policies. biscuit has the same restriction because biscuit uses the AWS APIs. However, if you're using the default key policy (as created by `biscuit kms init`), you can also use IAM policies to grant access to the key. Here's what you'll need to do:

1. Create an IAM policy that allows the KMS actions you want your developers to be able to perform, and lists all of the keys used by biscuit. Here's an example:

     ```
     {
         "Version": "2012-10-17",
         "Statement": [
             {
                 "Sid": "AllowEncryptWithMyKeys",
                 "Effect": "Allow",
                 "Action": [
                     "kms:GenerateDataKey",   // allows "put"
                     "kms:Decrypt"            // allows "get"
                 ],
                 "Resource": [
                     "arn:aws:kms:us-east-1:000000000000:key/abc",
                     "arn:aws:kms:us-west-1:000000000000:key/def",
                     "arn:aws:kms:us-west-2:000000000000:key/ghi"
                 ]
             }
         ]
     }
     ```
2. Attach that policy to the `developers` group.

This works because `biscuit kms init` attaches a KMS policy (which is a different kind of policy than an IAM policy) which enables IAM policies to allow access to the KMS keys. Here is the explanation [from the docs](http://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html#key-policy-default-allow-root-enable-iam):

```
The default key policy gives the AWS account (root user) that owns the CMK full access to the CMK, which accomplishes two things:

* Reduces the risk of the CMK becoming unmanageable.
* Enables IAM policies to allow access to the CMK.   <-- important
```

Another option is to use role assumption. This will allow you to use KMS grants but it complicates the developer experience by requiring them to assume a role prior to using the keys. Some consider this to be a more secure approach. Tools such as https://github.com/dcoker/awsmfa can mitigate the complexity.
