### ISSUE TITLE
Feature Request: Add support for shell format export

### ISSUE THREAD

**Issue by bobziuchkovski** [dcoker/biscuit#9]
Currently, `biscuit export` exports values in YAML format.  It would be terrific if biscuit supported exporting values in shell format (`export KEY="VALUE"`).  Then running `eval $(biscuit export)` from a shell script would load all k/v pairs into env vars.

We're evaluating biscuit for use with an application that follows 12-factor design.  The application expects to read all config from env vars.  In order to get this to work, we currently need to `biscuit export`, pipe the result to a file, parse the file as YAML, then format and evaluate relevant `export KEY="VALUE"` statements.  It would be so much nicer to have biscuit format that output directly.

Anyway, let me know if you're open to a pull request.  I'd be happy to submit one.

**Comment by dcoker** [comment]
Hi Bob -

Interesting! I can see how generating the `export` commands would be helpful. However, I know some biscuit users are storing values that contain quotes and other shell meta characters, and safely escaping the VALUE in ways that are compatible across platforms might be complicated. A workaround might be to use a shell loop so that the shell takes the burden of escaping the values properly:

```bash
for k in $(biscuit list); do
  export $k="$(biscuit get $k)"
done
```

That said, I would be happy to review a PR that adds a generic mechanism for formatting the data displayed on the console by any command (not just export). Example: `biscuit kms grants list --format json`.

Thanks!

**Comment by bobziuchkovski** [comment]
@dcoker Good points both on the cross-platform support and proper escaping.  I think you're right that this wouldn't work well.

I suppose one option would be to add some sort of `biscuit invoke` or something that has biscuit using os.SetEnv to inject the values and launching the rest of os.Args.  That ought to be cross-platform.  That said, maybe it's not that big of a deal to leave it up to the client to handle the decrypted values instead of biscuit.
